### PR TITLE
Improve CLI commands reference

### PR DESCRIPTION
**Pull request by neojp**
- Add table of contents with links to each command
- Add anchored headings to each command
- Add description to each command

Related #162

## Screenshots

image

---

image

---

image

### CODE REVIEW

**Comment by jenweber** [comment]
Hello! This is wonderful, thank you! I can help with the failing tests and build later today. We can configure the spell checker to ignore this page. I’m not sure why the build broke but it’s probably just a little thing.

**Comment by neojp** [comment]
Thank you! I was looking through the CI errors and was wondering why the build was failing. I'll try building it locally too.

**Comment by jenweber** [comment]
Ok, to exclude this page from spellchecking, add this line to `.remarkignore`:

```
guides/advanced-use/cli-commands-reference.md
```

The Netlify deploy is failing due to a problem with dependency caching, 100% unrelated to your changes. You can ignore that problem, and I'll see if I can sort out what's wrong separately.

**Review by jenweber — APPROVED** [review]
We can merge this as soon as the preview deploy & tests are green. The preview deploy is being debugged separately by me.

**Comment by neojp** [comment]
I decided to wrap the headings and any references to the CLI commands with `<code>`  to avoid the linter from erroring out. The CI tests are all green now! 🚀

**Pull request merged**
