### PR TITLE
Upgrade app to Ember 3.22

### LINKED ISSUE #197: Upgrade app to Ember 3.22 (Part 1 of 2)
## Problem

~Please wait till #198 has been completed and merged. Once that issue is complete, you should see `npm-run-all`, `ember-template-lint`, and `eslint` installed already.~ (This issue is unblocked now!)

If you run `npm outdated`, you will see that many packages can use an update. At the time of writing, I saw,

```bash
❯ npm outdated

Package                         Current   Wanted  Latest  Location
@ember/optional-features          1.3.0    1.3.0   2.0.0  @ember-learn/cli-guides
@glimmer/component                1.0.0    1.0.2   1.0.2  @ember-learn/cli-guides
@glimmer/tracking                 1.0.0    1.0.2   1.0.2  @ember-learn/cli-guides
alex                              7.1.0    7.1.0   9.0.1  @ember-learn/cli-guides
ember-auto-import                 1.5.3    1.6.0   1.6.0  @ember-learn/cli-guides
ember-cli                        3.16.1   3.16.2  3.21.2  @ember-learn/cli-guides
ember-cli-babel                  7.19.0   7.22.1  7.22.1  @ember-learn/cli-guides
ember-cli-fastboot                2.2.2    2.2.3   2.2.3  @ember-learn/cli-guides
ember-cli-htmlbars                4.3.1    4.4.0   5.3.1  @ember-learn/cli-guides
ember-cli-netlify                 0.3.1    0.3.1   0.4.1  @ember-learn/cli-guides
ember-cli-template-lint           1.0.0    1.0.0   2.0.2  @ember-learn/cli-guides
ember-data                       3.16.5   3.16.9  3.21.1  @ember-learn/cli-guides
ember-dictionary                  0.2.5    0.2.6   0.2.6  @ember-learn/cli-guides
ember-fetch                       7.1.0    7.1.0   8.0.2  @ember-learn/cli-guides
ember-resolver                    7.0.0    7.0.0   8.0.2  @ember-learn/cli-guides
ember-source                     3.16.8  3.16.10  3.21.1  @ember-learn/cli-guides
eslint-plugin-ember              7.13.0   7.13.0   9.0.0  @ember-learn/cli-guides
mocha                             5.2.0    5.2.0   8.1.3  @ember-learn/cli-guides
prember                           1.0.3    1.0.5   1.0.5  @ember-learn/cli-guides
qunit-dom                         1.2.0    1.5.0   1.5.0  @ember-learn/cli-guides
remark-cli                        8.0.0    8.0.1   8.0.1  @ember-learn/cli-guides
remark-lint                       7.0.0    7.0.1   7.0.1  @ember-learn/cli-guides
remark-preset-lint-consistent     3.0.0    3.0.1   3.0.1  @ember-learn/cli-guides
remark-preset-lint-recommended    4.0.0    4.0.1   4.0.1  @ember-learn/cli-guides
retext-indefinite-article         2.0.0    2.0.1   2.0.1  @ember-learn/cli-guides
unified                           9.0.0    9.2.0   9.2.0  @ember-learn/cli-guides
```

Moreover, the `cli-guides` app currently uses Ember `v3.16.8`. Let's upgrade the app to `v3.21.x` (or `v3.22.x` if it is available) for a regular maintenance.

### Part 1: Update packages

I may recommend updating packages in batches as shown below. (Hopefully, no major release introduced a breaking change that affects this app.)

After each batch update of packages, please push a commit so that the CI may check that lints and tests continue to pass.

- [ ] Update lint/test-related packages
  - alex
  - ~~Remove ember-cli-eslint, then install [eslint](https://github.com/eslint) to `devDependencies`~~
  - ~~Remove ember-cli-template-lint, then install [ember-template-lint](https://github.com/ember-template-lint/ember-template-lint) to `devDependencies`~~
  - eslint-plugin-ember
  - mocha
  - qunit-dom

- [ ] Update `remark`-related packages
  - remark-cli
  - remark-lint
  - remark-preset-lint-consistent
  - remark-preset-lint-recommended
  - retext-indefinite-article
  - unified

- [ ] Update Ember addons
  - ember-cli-fastboot
  - ember-cli-netlify
  - ember-dictionary
  - prember

- [ ] Update Ember-related packages (packages installed by default)
  - @ember/optional-features
  - @glimmer/component
  - @glimmer/tracking
  - ember-auto-import
  - ember-cli-babel
  - ember-cli-htmlbars
  - Remove ember-cli-uglify, then install [ember-cli-terser](https://github.com/ember-cli/ember-cli-terser) to `devDependencies`
  - ember-fetch
  - ember-resolver

- [ ] Update Ember with `ember-cli-update`
  - ember-cli
  - ember-data
  - ember-source

- [ ] ~~If running `ember-cli-update` didn't install `npm-run-all`, please install it under `devDependencies`. If it didn't _uninstall_ `ember-cli-eslint` and `ember-cli-template-lint`, please do so and install `eslint` and `ember-template-lint` instead.~~

### PR DESCRIPTION
**Pull request by maxwondercorn**
Upgrade Ember per #197 
- [x]  Update lint/test-related packages
- [x] Update remark-related packages
- [x] Update Ember addons
- [x]  Update Ember-related packages (packages installed by default)
- [x] Update Ember with ember-cli-update

Closes #197

### CODE REVIEW

**Comment by maxwondercorn** [comment]
The Alex linting issues were also present on master

**Comment by ijlee2** [comment]
Hi, @maxwondercorn. Thanks for working on upgrading the dependencies to their latest version.

When lint errors happen due to a package upgrade, I'd recommend adding the lint rule as an exception, as demonstrated in https://github.com/ember-learn/ember-website/pull/670/commits/9999b79b7a05c4b781fea2efe4d2450907a9be72. I can create a follow-up issue to fix the lint rules separately.

It looks you can edit `.alexrc` file. Can you try adding `retext-equality` to the list of allowed rules, see if this will help Travis CI to pass?

**Comment by maxwondercorn** [comment]
I am going to add `alex disable` comments for each error in the markdown files.  I think it's better to be specific than globally disabling them in `.alexrc`

There must have some type of regression. These were not flagged the last time I did a PR.  Some of the flagged words are relatively recent additions, but some  have been in the guides for a couple years.

**Comment by ijlee2** [comment]
Per file sounds good with me, thanks. I think `ember-cli` just released 3.22 version. If you'd like to upgrade the app to 3.22 instead, feel free to.

**Comment by ijlee2** [comment]
@maxwondercorn Looks like the Netlify deploy build failed due to this error:

```
12:21:32 PM: Build Error (broccoli-persistent-filter:Babel > [Babel: @ember-data/adapter]) in @ember-data/adapter/rest.js
12:21:32 PM: /opt/build/repo/@ember-data/adapter/rest.js: Imported DEPRECATE_NAJAX from @ember-data/private-build-infra/deprecations which is not a supported flag.
```

I think this is the related pull request: https://github.com/emberjs/data/pull/7230 . It seems to suggest installing `ember-fetch` to remove the deprecation, but we already have the latest package? Hmm...

**Comment by ijlee2** [comment]
According to a [Discord conversation](https://discord.com/channels/480462759797063690/486549196837486592/764973940648050688), it seems removing `node_modules` will help fix the error. I will clear the cache and restart the build.

**Comment by ijlee2** [comment]
Yep, clearing the cache worked. ✨

**Comment by maxwondercorn** [comment]
I did that locally and if fixed the issue but on the Netilfy build... Glad it's now working!!

**Comment by maxwondercorn** [comment]
@ijlee2 all upgrade steps for the 3.21 bump are completed

**Comment by ijlee2** [comment]
@maxwondercorn Thanks! I'll have a look tomorrow.

**Review by ijlee2 — APPROVED** [review]
@maxwondercorn Thank you for working on upgrading the CLI Guides app to `v3.22`! Always happy to see Ember apps running on the latest version.

I tested the deployed app by navigating between pages and the app continued to work without error. 💯

**Pull request merged**
