### PR TITLE
Uninstalled ember-cli-template-lint and ember-cli-eslint packages.

### PR DESCRIPTION
**Pull request by takshch**
# Description( Issue No - #198 ):

### CODE REVIEW

**Review by ijlee2 — COMMENTED** [review]
@takshch Looks good to me! Let's make 1 small change before merging this PR:

In `package.json`, can you update the `test` script to say,

```json
"scripts": {
  "test": "npm-run-all --aggregate-output --continue-on-error --parallel test:*""
}
```

By writing `npm-run-all test:*`, the `test` script will be able to run both `test:ember` and `test:node` scripts.

I realize it wasn't to see the differences in the scripts in the issue, sorry.

**Comment by ijlee2** [comment]
Your pull request description is a great start, I thought. I appreciated that you documented what you did (e.g. ran `npm run lint:hbs`) and what you saw (no errors).

**Comment by takshch** [comment]
@ijlee2 Required changes are made. Please review again.

**Review by ijlee2 — APPROVED** [review]
Thanks! You are now an open-source contributor! 🎉

**Pull request merged**
