### PR TITLE
add ember generate blueprints to cli reference

### PR DESCRIPTION
**Pull request by neojp**
This PR attempts to add additional CLI information for each `ember generate` blueprint provided by default. The blueprints are the following:

- ember-source
  - acceptance-test
  - component
  - component-addon
  - component-class
  - component-class-addon
  - component-test
  - controller
  - controller-test
  - helper
  - helper-test
  - initializer
  - initializer-addon
  - initializer-test
  - instance-initializer
  - instance-initializer-addon
  - instance-initializer-test
  - mixin
  - mixin-test
  - route
  - route-addon
  - route-test
  - service
  - service-test
  - template
  - util
  - util-test

- ember-data
  - adapter
  - adapter-test
  - model
  - model-test
  - serializer
  - serializer-test
  - transform
  - transform-test

- ember-cli
  - addon
  - addon-import
  - app
  - blueprint
  - http-mock
  - http-proxy
  - in-repo-addon
  - lib
  - server
  - vendor-shim

Related to #162

---

## Screenshot

image

### CODE REVIEW

**Comment by neojp** [comment]
CI is failing with the following lint error, but I can't reproduce it in my local machine.

image

I guess we probably should ignore this file from eslint. Should I add it to the `.eslintignore` file?

**Comment by maxwondercorn** [comment]
@neojp That's an error from Alex which catches insensitive writing.  You can override the error by putting this comment above the offending line

**Comment by neojp** [comment]
@maxwondercorn thanks, that worked! How would you disable this `retext-spell` lint rule?

image

**Comment by maxwondercorn** [comment]
@neojp Normally the words would be added to the `.local.dic` file in the project root. They should _not_ have to be added to the `.local.dic` file because they are surrounded by back-ticks.  

I'm not sure why they are being flagged because `ember-data` is used elsewhere and it's not flagged.

If you've done an npm install, you can run the markdown linting locally with the `npm run lint:md` command.  I'd be curious to see if the use of ember-data in the `appendix/common-issues.md` is flagged

**Comment by neojp** [comment]
> I'm not sure why they are being flagged because `ember-data` is used elsewhere and it's not flagged.

Ah! What happened is that I added backticks to avoid getting these linter errors from showing up. I wanted to remove those backticks by adding an ignore rule, but I couldn't figure it out how. Thanks for the info, I've added the values to the `.local.dic` and it's working now.

**Review by jenweber — APPROVED** [review]
Awesome, thank you!

**Pull request merged**
