### PR TITLE
Debug node code instructions

### PR DESCRIPTION
**Pull request by maxwondercorn**
Debugging ember-cli node code based on the Embermap.com [video](https://embermap.com/video/use-chrome-s-inspector-to-debug-an-addon). Instructions updated to match current Chrome version.

Alternate location may be with `Broccoli asset pipeline` as debugging broccoli issues is the primary use

### CODE REVIEW

**Comment by jenweber** [comment]
Another option for this content could be the page called "dev-tools". Right now the title is focused on Code Editors because I couldn't think of anything else that should go there, but I suspected there was something. We could rename that section to be "dev tools" and include your content there! What do you think?

Thanks for taking the time to write this up :)

**Comment by maxwondercorn** [comment]
However this fits into the overall vision of the docs works for me.  I'd imagine things will change a bit as content is flushed out

**Comment by Gaurav0** [comment]
@jenweber @locks Are there copyright concerns regarding content from an EmberMap video?

**Comment by maxwondercorn** [comment]
I thought about that before posting.  the video just shows that it can be done - that's where I learned about the node debugger.  This is the standard node [debugger](https://nodejs.org/api/debugger.html) on a node app.  

The video as posted doesn't work anymore because of changes in Chrome DevTools, which is why you need to the extension.  Which is probably why It's not visible on the site anymore. @jenweber @locks can make the call.

Reviewing the latest node documentation, I realized I can simplify it more by using `--inspect` instead of `--inspect-brk`

**Comment by maxwondercorn** [comment]
I combined the node debugging section with editor integrations and renamed it to Developer tools.  The intro paragraph (sentence) could be improved

**Comment by jenweber** [comment]
@Gaurav0 that's a good question. I'll ping the EmberMap creators privately.

**Comment by jenweber** [comment]
Thanks for your work @maxwondercorn and our friends at EmberMap! Merging this.

I chatted with @samselikoff and he says it is fine to use this content, without credit. I chatted with him a bit about helping new learners discover content outside the guides, and I have a few ideas of how to do that, moving forward.

**Pull request merged**
