### PR TITLE
Ember upgrade 3.16

### PR DESCRIPTION
**Pull request by vinodhrajamuralidharan**
connect https://github.com/ember-learn/cli-guides/issues/173
npm install -g ember-cli-update
ember-cli-update --to 3.16

### CODE REVIEW

**Comment by jenweber** [comment]
I can replicate the errors locally with `ember s --environment production`, if that's helpful to know.

**Comment by vinodhrajamuralidharan** [comment]
@jenweber yes, I tried that already as it was failing only in the pipeline. The actual issue is when I do that, the error is on 

pre-render /release/writing-addons/deploying failed with exception: FetchError: request to http://localhost/:7784undefined//localhost:7784/content/versions.json failed, reason: connect ECONNREFUSED 127.0.0.1:80

It has undefined for some reason. That's why it is failing.

**Comment by jenweber** [comment]
Ok, I’ll take a look at this tonight.

**Comment by jayjayjpg** [comment]
@jenweber @vinodhrajamuralidharan We (@mansona  and me) are also currently investigating if there's an issue with prember in the Netlify build step - will keep you posted if we can resolve the issue!

**Comment by jayjayjpg** [comment]
@vinodhrajamuralidharan Netlify deploys are unblocked [after an upgrade of the prember dependency](https://github.com/ember-learn/cli-guides/pull/177/commits/b864d3b50fd303081bbbf750bc6e5c7a3307a84c)! Can you git pull the changes and do another rebase of your feature branch onto the latest master? Then this should be ready to go already! :sparkles:

**Comment by vinodhrajamuralidharan** [comment]
@jayjayjpg seems it works now. Just it shows conflicts on package and package-lock.json and I don't have access permission to resolve that.

**Comment by mansona** [comment]
this looks like it still has conflict markers somewhere 🤔 maybe in the package-lock?

**Comment by vinodhrajamuralidharan** [comment]
@mansona yes it is in package-lock.json

**Pull request merged**
